agent/urls.py
# Copyright Evan Hazlett and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from django.conf.urls import patterns, url

urlpatterns = patterns('agent.views',
    url(r'^register/$', 'register', name='agent.register'),
    url(r'^containers/$', 'containers', name='agent.containers'),
    url(r'^images/$', 'images', name='agent.images'),
    url(r'^metrics/$', 'metrics', name='agent.metrics'),
)

applications/urls.py
# Copyright Evan Hazlett and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from django.conf.urls import patterns, url

urlpatterns = patterns('applications.views',
    url(r'^$', 'index', name='applications.index'),
    url(r'^create/$', 'create', name='applications.create'),
    url(r'^details/(?P<app_uuid>\w{32})/$', 'details',
        name='applications.details'),
    url(r'^(?P<app_uuid>\w{32})/delete/$', 'delete',
        name='applications.delete'),
    url(r'^(?P<app_uuid>\w{32})/containers/attach/$',
        'attach_containers', name='applications.attach_containers'),
    url(r'^(?P<app_uuid>\w{32})/containers/(?P<container_id>\w{12})/remove/$',
        'remove_container', name='applications.remove_container'),
)

shipyard/urls.py
# Copyright Evan Hazlett and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from django.conf.urls import patterns, include, url
from tastypie.api import Api
from django.contrib import admin
admin.autodiscover()

from containers.api import ContainerResource
from applications.api import ApplicationResource
from hosts.api import HostResource
from images.api import ImageResource

v1_api = Api(api_name='v1')
v1_api.register(ContainerResource())
v1_api.register(ApplicationResource())
v1_api.register(HostResource())
v1_api.register(ImageResource())

urlpatterns = patterns('',
    url(r'^$', 'shipyard.views.index', name='index'),
    url(r'^api/login', 'accounts.views.api_login', name='api_login'),
    url(r'^api/', include(v1_api.urls)),
    url(r'^agent/', include('agent.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^applications/', include('applications.urls')),
    url(r'^containers/', include('containers.urls')),
    url(r'^images/', include('images.urls')),
    url(r'^hosts/', include('hosts.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

applications/models.py
from django.db import models
from django.db.models.signals import post_save, pre_delete, m2m_changed
from django.contrib.auth.models import User
from containers.models import Container
from shipyard import utils
from django.utils.translation import ugettext as _
import uuid

PROTOCOL_CHOICES = (
    ('http', _('HTTP')),
    ('https', _('HTTPS')),
    ('tcp', _('TCP')),
)

def generate_uuid():
    return str(uuid.uuid4()).replace('-', '')

class Application(models.Model):
    uuid = models.CharField(max_length=36, null=True, blank=True, unique=True,
        default=generate_uuid)
    name = models.CharField(max_length=64, null=True)
    description = models.TextField(null=True, blank=True)
    domain_name = models.CharField(max_length=96, null=True,
        unique=True)
    host_interface = models.CharField(max_length=128, null=True, blank=True,
        help_text='Host interface your port is bound to or leave blank for default')
    backend_port = models.CharField(max_length=5, null=True)
    protocol = models.CharField(max_length=6, null=True,
        default='http', choices=PROTOCOL_CHOICES)
    containers = models.ManyToManyField(Container, null=True, blank=True,
        limit_choices_to={'is_running': True})
    owner = models.ForeignKey(User, null=True, blank=True)

    def __unicode__(self):
        return self.name

    def get_app_url(self):
        return '{0}://{1}'.format(self.protocol, self.domain_name)

    def get_memory_limit(self):
        mem = 0
        for c in self.containers.all():
            mem += c.get_memory_limit()
        return mem

    def save(self, *args, **kwargs):
        if self.pk is not None:
            original_domain = Application.objects.get(pk=self.pk).domain_name
            # check for changed domain
            if self.domain_name != original_domain:
                # if not original domain, remove hipache config
                utils.remove_hipache_config(original_domain)
        super(Application, self).save(*args, **kwargs)
        self.update_config()

    def update_config(self):
        utils.update_hipache(self.id)

def update_application_config(sender, **kwargs):
    # signal used for updating the manytomany containers field
    app = kwargs.get('instance')
    app.save()
    utils.update_hipache(app.id)

def remove_application_config(sender, **kwargs):
    app = kwargs.get('instance')
    utils.remove_hipache_config(app.domain_name)

m2m_changed.connect(update_application_config, sender=Application.containers.through)
pre_delete.connect(remove_application_config, sender=Application)

applications/forms.py
# Copyright Evan Hazlett and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from django import forms
from django.utils.translation import ugettext as _
from applications.models import Application
from containers.models import Container
from hosts.models import Host
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Field
from crispy_forms.bootstrap import FieldWithButtons, StrictButton, FormActions
from django.core.urlresolvers import reverse
from applications.models import PROTOCOL_CHOICES

def get_available_hosts():
    return Host.objects.filter(enabled=True)

class ApplicationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ApplicationForm, self).__init__(*args, **kwargs)
        # set height for container select
        container_list_length = len(Container.get_running())
        if container_list_length > 20:
            container_list_length = 20
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                None,
                'name',
                'description',
                'domain_name',
                'host_interface',
                'backend_port',
                'protocol',
                Field('containers', size=container_list_length),
            ),
            FormActions(
                Submit('save', _('Update'), css_class="btn btn-lg btn-success"),
            )
        )
        self.helper.form_id = 'form-create-application'
        self.helper.form_class = 'form-horizontal'
        self.helper.form_action = reverse('applications.views.create')

    def clean(self):
        data = super(ApplicationForm, self).clean()

        if len(data.get('containers', [])) == 0:
            return data

        port = data.get('backend_port')
        interface = data.get('host_interface') or '0.0.0.0'
        for c in data.get('containers', []):
            port_proto = "{0}/tcp".format(port)
            container_ports = c.get_ports()
            if not port_proto in container_ports:
                msg = _(u'Port %s is not available on the selected containers.' % port_proto)
                self._errors['backend_port'] = self.error_class([msg])
            if not container_ports.get(port_proto, {}).get(interface):
                msg = _(u'Port %s is not bound to the interface %s on the selected containers.' % (port_proto, interface))
                self._errors['host_interface'] = self.error_class([msg])

        return data

    class Meta:
        model = Application
        fields = ('name', 'description', 'domain_name', 'host_interface', 'backend_port',
            'protocol', 'containers')

class EditApplicationForm(forms.Form):
    uuid = forms.CharField(required=True, widget=forms.HiddenInput())
    name = forms.CharField(required=True)
    description = forms.CharField(required=False)
    domain_name = forms.CharField(required=True)
    host_interface = forms.CharField(required=False)
    backend_port = forms.CharField(required=True)
    protocol = forms.ChoiceField(required=True)

    def __init__(self, *args, **kwargs):
        super(EditApplicationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'form-edit-application'
        self.helper.form_class = 'form-horizontal'
        self.helper.form_action = reverse('applications.views.edit')
        self.helper.help_text_inline = True
        self.fields['protocol'].choices = PROTOCOL_CHOICES

applications/views.py
# Copyright Evan Hazlett and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from django.shortcuts import render_to_response, redirect
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.http import HttpResponse
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from applications.models import Application
from applications.forms import ApplicationForm, EditApplicationForm
from containers.models import Container

@login_required
def index(request):
    apps = Application.objects.filter(Q(owner=None) |
        Q(owner=request.user))
    ctx = {
        'applications': apps,
    }
    return render_to_response('applications/index.html', ctx,
        context_instance=RequestContext(request))

@login_required
def create(request):
    form = ApplicationForm()
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        form.owner = request.user
        if form.is_valid():
            app = form.save()
            return redirect(reverse('applications.views.index'))
    ctx = {
        'form': form
    }
    return render_to_response('applications/create_application.html', ctx,
        context_instance=RequestContext(request))

@login_required
def details(request, app_uuid=None):
    app = Application.objects.get(uuid=app_uuid)
    form = ApplicationForm(instance=app)
    if request.method == 'POST':
        form = ApplicationForm(request.POST, instance=app)
        if form.is_valid():
            form.save()
            try:
                app.update_config()
                messages.add_message(request, messages.INFO,
                    _('Application updated'))
                return redirect(reverse('applications.views.index'))
            except KeyError, e:
                messages.add_message(request, messages.ERROR,
                    _('Error updating hipache.  Invalid container port') + \
                        ': {}'.format(e[0]))
    ctx = {
        'application': app,
        'form': ApplicationForm(instance=app),
    }
    return render_to_response('applications/application_details.html', ctx,
        context_instance=RequestContext(request))

@login_required
def _details(request, app_uuid=None):
    app = Application.objects.get(uuid=app_uuid)
    attached_container_ids = [x.container_id for x in app.containers.all()]
    initial = {
        'name': app.name,
        'description': app.description,
        'domain_name': app.domain_name,
        'backend_port': app.backend_port,
        'protocol': app.protocol,
    }
    all_containers = Container.objects.filter(Q(owner=None) |
        Q(owner=request.user)) \
        .exclude(container_id__in=attached_container_ids)
    containers = [c for c in all_containers if c.get_meta().get('State', {}) \
        .get('Running') == True]
    ctx = {
        'application': app,
        'form_edit_application': EditApplicationForm(initial=initial),
        'containers': containers,
    }
    return render_to_response('applications/application_details.html', ctx,
        context_instance=RequestContext(request))

@login_required
#@owner_required # TODO
def delete(request, app_uuid=None):
    app = Application.objects.get(uuid=app_uuid)
    app.delete()
    return redirect(reverse('applications.views.index'))

@login_required
#@owner_required # TODO
def attach_containers(request, app_uuid=None):
    app = Application.objects.get(uuid=app_uuid)
    data = request.POST
    container_ids = data.getlist('containers', [])
    if container_ids:
        for i in container_ids:
            c = Container.objects.get(container_id=i)
            app.containers.add(c)
        app.save()
    return redirect(reverse('applications.views.details',
        kwargs={'app_uuid': app_uuid}))

@login_required
#@owner_required # TODO
def remove_container(request, app_uuid=None, container_id=None):
    app = Application.objects.get(uuid=app_uuid)
    c = Container.objects.get(container_id=container_id)
    app.containers.remove(c)
    app.save()
    return redirect(reverse('applications.views.details',
        kwargs={'app_uuid': app_uuid}))

applications/templates/applications/_common.html
{% load i18n %}

<script type="text/javascript">
    $(function() {
        $("li#sidenav-applications").addClass("active");
    });
    $("a.remove-application").click(function(){
        var appUuid = (this).getAttribute('data-application-uuid');
        if (confirm("{% trans 'Are you sure you want to remove this application?' %}")) {
            redirect("/applications/" + appUuid + "/delete/");
        }
        return false;
    });
</script>

applications/templates/applications/application_details.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load shipyard %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading heading-large">
        <span class="panel-title section-title">{% trans 'Application Details' %}</span>
        <span class="pull-right">
        </span>
    </div>
    <div class="panel-body">
        <div class="app-form">
            <form role="form" method="post">
            {% crispy form %}
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
</script>
{% endblock %}

applications/templates/applications/create_application.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load shipyard %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading heading-large">
        <span class="panel-title section-title">{% trans 'Create Application' %}</span>
        <span class="pull-right">
        </span>
    </div>
    <div class="panel-body">
        <div class="app-form">
            <form role="form" method="post">
            {% crispy form %}
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
</script>
{% endblock %}

applications/templates/applications/index.html
{% extends "base.html" %}
{% load i18n %}
{% load shipyard %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading heading-large">
        <span class="panel-title section-title">{% trans 'Applications' %}</span>
        <span class="section-toolbar">
        </span>
        <span class="pull-right">
            <a href="{% url 'applications.views.create' %}" class="btn btn-success btn-sm">{% trans 'Create' %}</a>
        </span>
    </div>
    <div class="panel-body">
        {% if applications %}
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>{% trans 'Name' %}</th>
                    <th>{% trans 'Description' %}</th>
                    <th>{% trans 'Domain Name' %}</th>
                    <th>{% trans 'Backend Port' %}</th>
                    <th>{% trans 'Protocol' %}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for app in applications %}
                <tr>
                    <td><a href="{% url 'applications.views.details' app_uuid=app.uuid %}">{{app.name}}</a></td>
                    <td>{{app.description}}</td>
                    <td><a href="{{app.get_app_url}}" target="_blank">{{app.domain_name}}</a></td>
                    <td>{{app.backend_port}}</td>
                    <td>{{app.get_protocol_display}}</td>
                    <td>
                        <div class="btn-group">
                            <a href="#" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-cog"></span>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu right">
                                <li><a href="#" class="remove-application" data-application-uuid="{{app.uuid}}">{% trans 'Remove Application' %}</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="text-muted">{% trans 'No applications' %}</div>
        {% endif %}
    </div>
</div>
{% include "applications/_common.html" %}
<script type="text/javascript">
</script>
{% endblock %}